// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Mapped$ReactTemplate = require("./Mapped.bs.js");
var Variants$ReactTemplate = require("./Variants.bs.js");

var component = ReasonReact.statelessComponent("Page");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var x = Variants$ReactTemplate.renderer(/* Image */-795439301);
      return React.createElement("div", {
                  className: "App"
                }, React.createElement("h1", undefined, "One Random Component"), React.createElement("h1", undefined, "Using Variants?"), React.createElement("div", undefined, x.name), React.createElement("h1", undefined, "Components"));
    });
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
