// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var LabJson = require("./lab.json");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

function props(json) {
  return {
          src: Json_decode.field("src", (function (param) {
                  return Json_decode.optional(Json_decode.string, param);
                }), json),
          w: Json_decode.field("w", Json_decode.$$float, json)
        };
}

function layout(json) {
  return {
          i: Json_decode.field("i", Json_decode.string, json),
          name: Json_decode.field("name", Json_decode.string, json),
          w: Json_decode.field("w", Json_decode.$$int, json),
          h: Json_decode.field("h", Json_decode.$$int, json),
          x: Json_decode.field("x", Json_decode.$$int, json),
          y: Json_decode.field("y", Json_decode.$$int, json),
          moved: Json_decode.field("y", (function (param) {
                  return Json_decode.optional(Json_decode.bool, param);
                }), json),
          static: Json_decode.field("y", (function (param) {
                  return Json_decode.nullable(Json_decode.bool, param);
                }), json)
        };
}

function style(json) {
  return {
          display: Json_decode.field("display", Json_decode.string, json),
          maxWidth: Json_decode.field("maxWidth", Json_decode.string, json)
        };
}

function component(json) {
  return {
          name: Json_decode.field("name", Json_decode.string, json),
          type: Json_decode.field("type", Json_decode.string, json),
          props: Json_decode.field("props", props, json),
          style: Json_decode.field("style", style, json),
          examples: Json_decode.field("examples", (function (param) {
                  return Json_decode.array(Json_decode.string, param);
                }), json)
        };
}

function lab(json) {
  return {
          name: Json_decode.field("name", Json_decode.string, json),
          library: Json_decode.field("library", Json_decode.string, json),
          layout: Json_decode.field("layout", (function (param) {
                  return Json_decode.array(layout, param);
                }), json),
          components: Json_decode.field("components", (function (param) {
                  return Json_decode.array(component, param);
                }), json)
        };
}

var Decode = /* module */[
  /* props */props,
  /* layout */layout,
  /* style */style,
  /* component */component,
  /* lab */lab
];

var lab$1 = lab(LabJson);

console.log(lab$1);

console.log(lab$1.components);

exports.Decode = Decode;
exports.lab = lab$1;
/* lab Not a pure module */
