// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var LabJson = require("./lab.json");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

function layout(json) {
  return {
          i: Json_decode.field("i", Json_decode.string, json),
          name: Json_decode.field("name", Json_decode.string, json),
          w: Json_decode.field("w", Json_decode.$$int, json),
          h: Json_decode.field("h", Json_decode.$$int, json),
          x: Json_decode.field("x", Json_decode.$$int, json),
          y: Json_decode.field("y", Json_decode.$$int, json),
          moved: Json_decode.field("y", (function (param) {
                  return Json_decode.optional(Json_decode.bool, param);
                }), json),
          static: Json_decode.field("y", (function (param) {
                  return Json_decode.optional(Json_decode.bool, param);
                }), json)
        };
}

function hover(json) {
  return {
          opacity: Json_decode.field("opacity", Json_decode.$$int, json),
          transition: Json_decode.field("transition", Json_decode.string, json)
        };
}

function active(json) {
  return {
          opacity: Json_decode.field("opacity", Json_decode.$$int, json),
          transition: Json_decode.field("transition", Json_decode.string, json)
        };
}

function props(json) {
  return {
          src: Json_decode.optional(Json_decode.string, json),
          w: Json_decode.optional(Json_decode.$$int, json),
          mt: Json_decode.optional(Json_decode.$$int, json),
          mb: Json_decode.optional(Json_decode.$$int, json),
          my: Json_decode.optional(Json_decode.$$int, json),
          fontSize: Json_decode.optional((function (param) {
                  return Json_decode.array(Json_decode.$$int, param);
                }), json),
          fontWeight: Json_decode.optional(Json_decode.string, json),
          color: Json_decode.optional(Json_decode.string, json),
          borderColor: Json_decode.optional(Json_decode.string, json),
          hover: Json_decode.optional(hover, json),
          active: Json_decode.optional(active, json)
        };
}

function style(json) {
  return {
          display: Json_decode.field("display", (function (param) {
                  return Json_decode.optional(Json_decode.string, param);
                }), json),
          maxWidth: Json_decode.field("maxWidth", (function (param) {
                  return Json_decode.optional(Json_decode.string, param);
                }), json),
          textTransform: Json_decode.field("textTransform", (function (param) {
                  return Json_decode.optional(Json_decode.string, param);
                }), json),
          letterSpacing: Json_decode.field("letterSpacing", (function (param) {
                  return Json_decode.optional(Json_decode.string, param);
                }), json),
          lineHeight: Json_decode.field("lineHeight", (function (param) {
                  return Json_decode.optional(Json_decode.string, param);
                }), json),
          textDecoration: Json_decode.field("textDecoration", (function (param) {
                  return Json_decode.optional(Json_decode.string, param);
                }), json),
          whiteSpace: Json_decode.field("whiteSpace", (function (param) {
                  return Json_decode.optional(Json_decode.string, param);
                }), json),
          transition: Json_decode.field("transition", (function (param) {
                  return Json_decode.optional(Json_decode.string, param);
                }), json),
          opacity: Json_decode.field("opacity", (function (param) {
                  return Json_decode.optional(Json_decode.$$int, param);
                }), json),
          height: Json_decode.field("height", (function (param) {
                  return Json_decode.optional(Json_decode.string, param);
                }), json),
          width: Json_decode.field("width", (function (param) {
                  return Json_decode.optional(Json_decode.string, param);
                }), json),
          overflow: Json_decode.field("overflow", (function (param) {
                  return Json_decode.optional(Json_decode.string, param);
                }), json),
          textAlign: Json_decode.field("textAlign", (function (param) {
                  return Json_decode.optional(Json_decode.string, param);
                }), json)
        };
}

function component(json) {
  return {
          name: Json_decode.field("name", Json_decode.string, json),
          type: Json_decode.field("type", Json_decode.string, json),
          props: Json_decode.field("props", props, json),
          style: Json_decode.field("style", style, json),
          examples: Json_decode.field("examples", (function (param) {
                  return Json_decode.array(Json_decode.string, param);
                }), json)
        };
}

function lab(json) {
  return {
          name: Json_decode.field("name", Json_decode.string, json),
          library: Json_decode.field("library", Json_decode.string, json),
          layout: Json_decode.field("layout", (function (param) {
                  return Json_decode.array(layout, param);
                }), json),
          components: Json_decode.field("components", (function (param) {
                  return Json_decode.array(component, param);
                }), json)
        };
}

var Decode = /* module */[
  /* layout */layout,
  /* hover */hover,
  /* active */active,
  /* props */props,
  /* style */style,
  /* component */component,
  /* lab */lab
];

var lab$1 = lab(LabJson);

console.log(lab$1);

console.log(lab$1.components);

exports.Decode = Decode;
exports.lab = lab$1;
/* lab Not a pure module */
