// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var $$Map = require("bs-platform/lib/js/map.js");
var List = require("bs-platform/lib/js/list.js");
var Curry = require("bs-platform/lib/js/curry.js");
var $$String = require("bs-platform/lib/js/string.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var DCode$ReactTemplate = require("./DCode.bs.js");

var StringMap = $$Map.Make([$$String.compare]);

var components = Belt_List.fromArray(DCode$ReactTemplate.lab.components);

console.log(List.length(components));

function getComponentMap(myList) {
  return List.fold_left((function (map, component) {
                return Curry._3(StringMap[/* add */3], component.name, component, map);
              }), StringMap[/* empty */0], myList);
}

var componentMap = getComponentMap(components);

Curry._2(StringMap[/* iter */9], (function (name, component) {
        console.log("key:" + (String(name) + (", val:" + (String(component) + ""))));
        return /* () */0;
      }), componentMap);

var test = Curry._2(StringMap[/* find */21], "Image", componentMap);

console.log(test.name);

console.log(test.examples);

exports.StringMap = StringMap;
exports.components = components;
exports.getComponentMap = getComponentMap;
exports.componentMap = componentMap;
exports.test = test;
/* StringMap Not a pure module */
