// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Mapped$ReactTemplate = require("./Mapped.bs.js");

function renderComponentToString(component) {
  if (component >= 83047816) {
    if (component >= 747849793) {
      if (component >= 936573133) {
        if (component >= 980392437) {
          if (component !== 1008382723) {
            if (component >= 1030312810) {
              if (component >= 1055663537) {
                return "PanelText";
              } else {
                return "TileTitle";
              }
            } else if (component >= 1012541212) {
              return "PanelSubtitle";
            } else {
              return "Center";
            }
          } else {
            return "StackoverflowIcon";
          }
        } else if (component >= 956035003) {
          if (component >= 967143678) {
            return "PanelLink";
          } else {
            return "ProducthuntIcon";
          }
        } else if (component >= 936769358) {
          return "Tile";
        } else {
          return "Text";
        }
      } else if (component >= 814486425) {
        if (component !== 841039691) {
          if (component >= 858945253) {
            if (component >= 925519251) {
              return "SectionTitle";
            } else {
              return "Meta";
            }
          } else if (component >= 848054398) {
            return "List";
          } else {
            return "Icon";
          }
        } else {
          return "CardImage";
        }
      } else if (component >= 782237951) {
        if (component >= 787543097) {
          return "Avatar";
        } else {
          return "SoundcloudIcon";
        }
      } else if (component >= 747850224) {
        return "Card";
      } else {
        return "Caps";
      }
    } else if (component >= 443153085) {
      if (component >= 610281319) {
        if (component !== 686820809) {
          if (component >= 728235971) {
            if (component >= 734224197) {
              return "CodepenIcon";
            } else {
              return "CardKicker";
            }
          } else if (component >= 695740268) {
            return "TwitterIcon";
          } else {
            return "TextLink";
          }
        } else {
          return "SlackIcon";
        }
      } else if (component >= 492288731) {
        if (component >= 562396850) {
          return "BigButton";
        } else {
          return "SnapchatIcon";
        }
      } else if (component >= 449640948) {
        return "PageBG";
      } else {
        return "CardText";
      }
    } else if (component >= 311537030) {
      if (component !== 352440247) {
        if (component >= 402450013) {
          if (component >= 426071310) {
            return "EtsyIcon";
          } else {
            return "NavLink";
          }
        } else if (component >= 354633226) {
          return "CardLink";
        } else {
          return "TileSubtitle";
        }
      } else {
        return "PanelKicker";
      }
    } else if (component >= 196390053) {
      if (component >= 242538002) {
        return "Button";
      } else {
        return "PanelAlt";
      }
    } else if (component >= 152781788) {
      return "YoutubeIcon";
    } else {
      return "CardTitle";
    }
  } else if (component >= -601714436) {
    if (component >= -283851833) {
      if (component >= -3095041) {
        if (component !== 3405105) {
          if (component >= 58691133) {
            if (component >= 75391058) {
              return "Flexbox";
            } else {
              return "VimeoIcon";
            }
          } else if (component >= 4153924) {
            return "Svg";
          } else {
            return "FacebookIcon";
          }
        } else {
          return "Div";
        }
      } else if (component >= -10071887) {
        if (component >= -8082985) {
          return "PanelImage";
        } else {
          return "ListItem";
        }
      } else if (component >= -61399625) {
        return "LinkedinIcon";
      } else {
        return "BlockLink";
      }
    } else if (component >= -515484383) {
      if (component !== -510591852) {
        if (component >= -359178963) {
          if (component >= -321263038) {
            return "KickstarterIcon";
          } else {
            return "TileImage";
          }
        } else if (component >= -423893276) {
          return "NpmIcon";
        } else {
          return "Container";
        }
      } else {
        return "SiteHeader";
      }
    } else if (component >= -545003529) {
      if (component >= -525226213) {
        return "TileText";
      } else {
        return "CardComposite";
      }
    } else if (component >= -592088536) {
      return "CardSubtitle";
    } else {
      return "GitHubIcon";
    }
  } else if (component >= -741941836) {
    if (component >= -668676951) {
      if (component !== -666038836) {
        if (component >= -621262933) {
          if (component >= -613746072) {
            return "TileLink";
          } else {
            return "InstagramIcon";
          }
        } else if (component >= -632551519) {
          return "TileKicker";
        } else {
          return "PageTitle";
        }
      } else {
        return "Capitalize";
      }
    } else if (component >= -716750517) {
      if (component >= -709855200) {
        return "HorizontalRule";
      } else {
        return "ListItemLink";
      }
    } else if (component >= -725972077) {
      return "PinterestIcon";
    } else {
      return "Papercraft";
    }
  } else if (component >= -796923164) {
    if (component >= -766074860) {
      if (component >= -755654248) {
        return "LinkList";
      } else {
        return "PanelTitle";
      }
    } else if (component >= -795439301) {
      return "Image";
    } else {
      return "Panel";
    }
  } else if (component >= -831743949) {
    if (component >= -806287783) {
      return "DribbbleIcon";
    } else {
      return "IconLink";
    }
  } else if (component >= -1020508761) {
    return "PageSubtitle";
  } else {
    return "BehanceIcon";
  }
}

function renderer(component) {
  return Mapped$ReactTemplate.find(renderComponentToString(component));
}

exports.renderComponentToString = renderComponentToString;
exports.renderer = renderer;
/* Mapped-ReactTemplate Not a pure module */
